### ISSUE TITLE
Initial Plan

### ISSUE THREAD

**Issue by Ben-Ackerman** [Ben-Ackerman/climbing-training-tracker#1]
## Plan (TODOs)
You will enter app and provide login (no create user page just preconfigured users)

### Stage 1
[] Once you enter the app you will have a button for new climbing session or view graphs
[] When you enter new sessions it should ask indoor or outdoor.
[] extra the session should let you enter meta data of location, how I feel that day (Subjective), Did I warm up (with a textbox for warm up notes).
[] Once session is open there should be a form to submit climbs.  Outdoor climbs should ask for route names indoor should not.  Climbs should colloct, grade, attempts, number of sends, and labels (for things like overhang, compression, slab, face, roof, strong, shouldery, fingery, slopy, juggy, tricky feet, etc.  Climb should also collect subjective difficulty at start,  Then there should be a button to close and save climb where we collect the subjective difficulty at end.  When closing there should also be a notes for things to work on to make easier (prompt user to keep it short)
[] Have a button to close session that collects the Subjective difficulty of climb.

### Stage 2 
[] Create a few graphs that capture how climbing is going.  Right now most interesting would be an over all volume number, a pyramid graph and bar chart of climbs by label.

### Stage 2.5
[] could we have session location names and route names auto complete suggestions when typing

Stage 3 nice to have
[] Real user sign up. 
[] custom labels per user.  
Export to csv []

Technical Plan
Use golang as language.  Teml and htmx for webpage rendering.  Sqlite on a volume as db

**Comment by Ben-Ackerman** [comment]
Endpoints.

- [ ] /user

- This page should have new session button and view graphs button that link to the sessions page and graphs page.  (maybe embed those pages instead of link.  That is decision for latter.

- [ ] /user/session (table of sessions) (GET/PUT/POST/DELETE)
- This page should contain a table of all the users sessions, and have a button for adding a new session

- [ ] /user/session/# (GET/PUT/POST/DELETE)
- This page should include all the metadata about a session and have delete/save/complete buttons.  Complete should prompt the user for closing details and validate all climbs are closed first

- [ ] /user/session/#/climb (GET/PUT/POST/DELETE)
- This page should contain a table of all the climbs in a session, and include a button for adding a new climbs.

- [ ] /user/session/#/climb/# (GET/PUT/POST/DELETE)
- This page will contain form data about the climb.  Should have delete/save/complete buttons.  Complete should prompt user to fill out closing details before saving.

- [ ] /user/graph (GET)
- Used to get page that describes the user

- [ ] /user/label (GET/PUT/POST/DELETE)
- This will allow us to change the labels used to describe climbs.

- [ ] /user/settings (GET)

- [ ] /user/settings/#name (GET/PUT/POST/DELETE)
- thought here is to update things like grade types aka font vs v grades

**Comment by Ben-Ackerman** [comment]
Tips to get started https://www.youtube.com/watch?v=wttTTFVrQiw
